import {useEffect,useState,useRef} from 'react';
import {ArrowLeft,Check,ChevronRight,MessageCircle,Phone,PhoneOff,Search,Send,Shield,UserPlus,Users,X} from 'lucide-react';
import {supabase} from '../lib/supabase';
import type {MediaItem} from '../types';

type Profile={id:string;username:string;display_name:string;avatar_url?:string|null};
type Friendship={id:string;requester_id:string;addressee_id:string;status:string};
type Permission={id:string;owner_id:string;viewer_id:string;status:string};
type Message={id:string;sender_id:string;recipient_id:string;body:string;created_at:string};

export function FrameSocial({uid,guest,onOpenLibrary,onCall}:{uid:string;guest:boolean;onOpenLibrary:(id:string)=>void;onCall:(friend:Profile)=>void}){
 const [friends,setFriends]=useState<Friendship[]>([]),[profiles,setProfiles]=useState<Record<string,Profile>>({}),[permissions,setPermissions]=useState<Permission[]>([]);
 const [selected,setSelected]=useState<Profile|null>(null),[query,setQuery]=useState(''),[results,setResults]=useState<Profile[]>([]),[messages,setMessages]=useState<Message[]>([]),[draft,setDraft]=useState('');
 const load=async()=>{
  const client=supabase;if(!client||guest)return;
  const {data:f}=await client.from('friendships').select('*').or('requester_id.eq.'+uid+',addressee_id.eq.'+uid);
  const fs=(f||[]) as Friendship[];setFriends(fs);
  const ids=[...new Set(fs.flatMap(x=>[x.requester_id,x.addressee_id]).filter(x=>x!==uid))];
  if(ids.length){const {data:p}=await client.from('profiles').select('id,username,display_name,avatar_url').in('id',ids);setProfiles(Object.fromEntries(((p||[]) as Profile[]).map(p=>[p.id,p])))}
  const {data:p}=await client.from('library_permissions').select('*').or('owner_id.eq.'+uid+',viewer_id.eq.'+uid);setPermissions((p||[]) as Permission[]);
 };
 useEffect(()=>{void load();if(guest)return;const t=window.setInterval(()=>void load(),5000);return()=>window.clearInterval(t)},[uid,guest]);
 useEffect(()=>{if(!supabase||guest||!selected)return;const loadMessages=async()=>{const client=supabase;if(!client)return;const {data}=await client.from('friend_messages').select('*').or('and(sender_id.eq.'+uid+',recipient_id.eq.'+selected.id+'),and(sender_id.eq.'+selected.id+',recipient_id.eq.'+uid+')').order('created_at',{ascending:true});setMessages((data||[]) as Message[])};void loadMessages();const t=window.setInterval(()=>void loadMessages(),2500);return()=>window.clearInterval(t)},[selected?.id,uid,guest]);
 if(guest)return <div className="page"><div className="social-lock"><Users size={28}/><h2>Friends is account-only</h2><p>Sign in to use usernames, private chat, permission-based library sharing and voice calls.</p></div></div>;
 const accepted=friends.filter(x=>x.status==='accepted').map(x=>profiles[x.requester_id===uid?x.addressee_id:x.requester_id]).filter(Boolean);
 const incoming=friends.filter(x=>x.status==='pending'&&x.addressee_id===uid);
 const search=async()=>{const client=supabase;if(query.trim().length<2||!client)return;const {data}=await client.from('profiles').select('id,username,display_name,avatar_url').ilike('username','%'+query.trim()+'%').neq('id',uid).limit(10);setResults((data||[]) as Profile[])};
 const add=async(id:string)=>{const client=supabase;if(client)await client.from('friendships').insert({requester_id:uid,addressee_id:id,status:'pending'});setResults(results.filter(x=>x.id!==id))};
 const accept=async(id:string)=>{const client=supabase;if(client)await client.from('friendships').update({status:'accepted'}).eq('id',id).eq('addressee_id',uid);await load()};
 const send=async()=>{const client=supabase;if(!client||!selected||!draft.trim())return;const body=draft.trim();setDraft('');await client.from('friend_messages').insert({sender_id:uid,recipient_id:selected.id,body})};
 const shareState=(id:string)=>permissions.find(p=>p.owner_id===id&&p.viewer_id===uid)?.status||'none';
 const askLibrary=async()=>{const client=supabase;if(!client||!selected)return;await client.from('library_permissions').upsert({owner_id:selected.id,viewer_id:uid,status:'pending'},{onConflict:'owner_id,viewer_id'});await load()};
 const incomingShares=permissions.filter(p=>p.owner_id===uid&&p.status==='pending');
 const allow=async(id:string)=>{const client=supabase;if(client)await client.from('library_permissions').update({status:'accepted'}).eq('id',id).eq('owner_id',uid);await load()};
 return <div className="page"><div className="page-heading"><div><small>PRIVATE SOCIAL SPACE</small><h1>Friends</h1><p>Find people by username, chat, call and share your library only with permission.</p></div></div>
  <div className="friend-search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&void search()} placeholder="Search username…"/><button className="primary" onClick={()=>void search()}><Search size={15}/>Find</button></div>
  {results.length>0&&<div className="people-results">{results.map(p=><div key={p.id}><span className="person-avatar">{(p.display_name||p.username)[0].toUpperCase()}</span><section><b>{p.display_name||p.username}</b><small>@{p.username}</small></section><button className="secondary" onClick={()=>void add(p.id)}><UserPlus size={15}/>Add</button></div>)}</div>}
  <div className="social-grid"><section className="social-panel"><div className="section-title"><div><small>REQUESTS</small><h2>Incoming</h2></div><span>{incoming.length}</span></div>{incoming.length?incoming.map(x=><div className="request-row" key={x.id}><span>@{profiles[x.requester_id]?.username||'user'}</span><button className="primary" onClick={()=>void accept(x.id)}><Check size={14}/>Accept</button></div>):<p className="muted">No pending requests.</p>}</section><section className="social-panel"><div className="section-title"><div><small>YOUR PEOPLE</small><h2>Friends</h2></div><span>{accepted.length}</span></div>{accepted.length?accepted.map(p=><button className={selected?.id===p.id?'friend-row active':'friend-row'} key={p.id} onClick={()=>setSelected(p)}><span className="person-avatar">{(p.display_name||p.username)[0].toUpperCase()}</span><span><b>{p.display_name||p.username}</b><small>@{p.username}</small></span><ChevronRight size={16}/></button>):<p className="muted">Add friends by username.</p>}</section></div>
  {selected&&<section className="chat-panel"><header><div><b>{selected.display_name||selected.username}</b><small>@{selected.username}</small></div><div className="chat-actions"><button className="secondary" onClick={()=>void askLibrary()}>{shareState(selected.id)==='accepted'?'Library shared':shareState(selected.id)==='pending'?'Request sent':'Ask to view library'}</button><button className="secondary" onClick={()=>onCall(selected)}><Phone size={15}/>Voice</button></div></header><div className="chat-messages">{messages.length?messages.map(m=><div key={m.id} className={m.sender_id===uid?'mine':'theirs'}><span>{m.body}</span><small>{new Date(m.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</small></div>):<div className="chat-empty"><MessageCircle size={22}/>Start the conversation.</div>}</div><form className="chat-input" onSubmit={e=>{e.preventDefault();void send()}}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder="Message…"/><button className="primary"><Send size={16}/></button></form>{shareState(selected.id)==='accepted'&&<button className="view-library" onClick={()=>onOpenLibrary(selected.id)}>Open shared library <ChevronRight size={15}/></button>}</section>}
  {incomingShares.length>0&&<section className="social-panel permission-panel"><div className="section-title"><div><small>LIBRARY ACCESS</small><h2>Requests to see yours</h2></div><span>{incomingShares.length}</span></div>{incomingShares.map(p=><div className="request-row" key={p.id}><span>@{profiles[p.viewer_id]?.username||'friend'} wants access.</span><button className="primary" onClick={()=>void allow(p.id)}><Shield size={14}/>Allow</button></div>)}</section>}
 </div>;
}

export function VoiceCall({uid,friend,close}:{uid:string;friend:Profile;close:()=>void}){
 const [state,setState]=useState<'idle'|'calling'|'ringing'|'connected'>('idle'),[incoming,setIncoming]=useState<any>(null),[error,setError]=useState('');
 const pc=useRef<RTCPeerConnection|null>(null),stream=useRef<MediaStream|null>(null),channel=useRef<any>(null),audio=useRef<HTMLAudioElement|null>(null),ice=useRef<any[]>([]);
 const room='frame-voice-'+[uid,friend.id].sort().join('-');
 const cleanup=(notify:boolean)=>{if(notify)void channel.current?.send({type:'broadcast',event:'voice',payload:{from:uid,type:'hangup'}});pc.current?.close();pc.current=null;stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;ice.current=[];setIncoming(null);setState('idle')};
 useEffect(()=>{const client=supabase;if(!client)return;const c=client.channel(room);channel.current=c;c.on('broadcast',{event:'voice'},async({payload}:any)=>{if(payload?.from===uid)return;if(payload?.type==='offer'){setIncoming(payload.offer);setState('ringing')}else if(payload?.type==='answer'&&pc.current){await pc.current.setRemoteDescription(payload.answer);for(const x of ice.current)await pc.current.addIceCandidate(x);ice.current=[];setState('connected')}else if(payload?.type==='ice'){if(pc.current?.remoteDescription)void pc.current.addIceCandidate(payload.candidate);else ice.current.push(payload.candidate)}else if(payload?.type==='hangup')cleanup(false)}).subscribe();return()=>{void c.unsubscribe();cleanup(false)}},[room,uid]);
 const peer=async()=>{if(!navigator.mediaDevices?.getUserMedia)throw new Error('Microphone calls are not supported in this browser.');const s=await navigator.mediaDevices.getUserMedia({audio:true});stream.current=s;const p=new RTCPeerConnection({iceServers:[{urls:'stun:stun.l.google.com:19302'}]});s.getTracks().forEach(t=>p.addTrack(t,s));p.onicecandidate=e=>{if(e.candidate)void channel.current?.send({type:'broadcast',event:'voice',payload:{from:uid,type:'ice',candidate:e.candidate}})};p.ontrack=e=>{if(audio.current){audio.current.srcObject=e.streams[0]||new MediaStream([e.track]);void audio.current.play().catch(()=>{})}};pc.current=p;return p};
 const start=async()=>{try{setError('');setState('calling');const p=await peer();const offer=await p.createOffer();await p.setLocalDescription(offer);await channel.current?.send({type:'broadcast',event:'voice',payload:{from:uid,type:'offer',offer:p.localDescription}});setState('ringing')}catch(e){setError(e instanceof Error?e.message:'Could not access microphone.');cleanup(false)}};
 const answer=async()=>{try{setError('');const p=await peer();await p.setRemoteDescription(incoming);for(const x of ice.current)await p.addIceCandidate(x);ice.current=[];const a=await p.createAnswer();await p.setLocalDescription(a);await channel.current?.send({type:'broadcast',event:'voice',payload:{from:uid,type:'answer',answer:p.localDescription}});setIncoming(null);setState('connected')}catch(e){setError(e instanceof Error?e.message:'Could not answer.');cleanup(false)}};
 const end=()=>{cleanup(true);close()};
 return <div className="voice-overlay"><section className="voice-card"><div className="voice-orb"><Phone size={28}/></div><small>VOICE CHAT</small><h2>{friend.display_name||friend.username}</h2><p>{incoming?'Incoming call':state==='calling'?'Connecting…':state==='ringing'?'Calling…':state==='connected'?'Connected':'Audio only'}</p>{error&&<div className="inline-error">{error}</div>}<audio ref={audio} autoPlay playsInline/><div className="voice-actions">{incoming?<><button className="primary" onClick={()=>void answer()}><Phone size={17}/>Answer</button><button className="secondary" onClick={end}><PhoneOff size={17}/>Decline</button></>:state!=='idle'?<button className="danger" onClick={end}><PhoneOff size={17}/>End call</button>:<><button className="primary" onClick={()=>void start()}><Phone size={17}/>Start call</button><button className="secondary" onClick={close}>Cancel</button></>}</div></section></div>;
}
