import {useMemo,useState} from 'react';
import {ExternalLink,Search,Users,X,CalendarDays,Mic2} from 'lucide-react';

type Character={id:number;name:string;alias:string;role:string;crew:string;bio:string;goal:string};
const rows=[
[1,'Monkey D. Luffy','Straw Hat','Captain','Straw Hat Pirates','The upbeat captain who can stretch his body after eating a Devil Fruit. He values freedom and his friends above fame.','Become King of the Pirates'],
[2,'Roronoa Zoro','Pirate Hunter','Swordsman','Straw Hat Pirates','A focused swordsman known for his Three-Sword Style and unwavering loyalty.','Become the world’s greatest swordsman'],
[3,'Nami','Cat Burglar','Navigator','Straw Hat Pirates','A clever navigator, weather expert and cartographer who guides the crew across the seas.','Draw a map of the entire world'],
[4,'Usopp','God Usopp','Sniper and inventor','Straw Hat Pirates','A creative marksman who relies on clever tools, stories and improvisation.','Become a brave warrior of the sea'],
[5,'Sanji','Stealth Black / Soba Mask','Cook','Straw Hat Pirates','The crew’s cook, known for his culinary skill and kick-focused style.','Find the All Blue'],
[6,'Tony Tony Chopper','Cotton Candy Lover','Doctor','Straw Hat Pirates','A reindeer with human-like traits who combines medical knowledge with special transformations.','Become a doctor who can cure any disease'],
[7,'Nico Robin','Devil Child','Archaeologist','Straw Hat Pirates','A calm scholar who can read Poneglyphs and uncover fragments of lost history.','Discover the true history of the world'],
[8,'Franky','Cyborg','Shipwright','Straw Hat Pirates','A cyborg shipwright and inventor who built the Thousand Sunny.','Build a ship that reaches the end of the world'],
[9,'Brook','Soul King','Musician','Straw Hat Pirates','A living skeleton and musician whose Devil Fruit brought him back to life.','Reunite with Laboon'],
[10,'Jinbe','Knight of the Sea','Helmsman','Straw Hat Pirates','A fish-man and experienced helmsman known for calm judgement and honour.','Help humans and fish-men coexist'],
[11,'Nefertari Vivi','Princess Vivi','Princess','Alabasta; former Straw Hat companion','The compassionate princess who travelled with the Straw Hats to protect Alabasta.','Protect Alabasta and its people'],
[12,'Portgas D. Ace','Fire Fist','Pirate commander','Whitebeard Pirates; formerly Spade Pirates','Luffy’s sworn older brother, remembered for his warmth and devotion to family.','Live freely and honour his family'],
[13,'Sabo','Chief of Staff','Revolutionary leader','Revolutionary Army','Luffy and Ace’s sworn brother who works to challenge oppression.','Fight for freedom and protect his brothers’ legacy'],
[14,'Yamato','Oni Princess','Wano warrior','Wano','A powerful Wano native inspired by Kozuki Oden’s journals and ideals.','Follow Oden’s path and explore the world'],
[15,'Trafalgar D. Water Law','Surgeon of Death','Captain and doctor','Heart Pirates','A strategic pirate and surgeon whose Devil Fruit creates a space for precise operations.','Uncover the meaning of the Will of D.'],
[16,'Eustass Kid','Captain Kid','Pirate captain','Kid Pirates','An ambitious captain who uses magnetic abilities to manipulate metal.','Reach the top of the pirate world'],
[17,'Boa Hancock','Pirate Empress','Captain','Kuja Pirates; Amazon Lily','The ruler of Amazon Lily, known for confidence, Haki and a petrification ability.','Protect Amazon Lily and her loved ones'],
[18,'Carrot','Mink warrior','Scout','Mokomo Dukedom','An energetic rabbit mink with exceptional agility and sharp senses.','Carry Pedro’s hopes forward'],
[19,'Gol D. Roger','Pirate King','Pirate captain','Roger Pirates','The legendary pirate who reached the final island and began a new era of piracy.','Reach the end of the Grand Line'],
[20,'Edward Newgate','Whitebeard','Pirate captain','Whitebeard Pirates','A legendary pirate who treated his crew as family.','Have a family'],
[21,'Monkey D. Garp','Hero of the Marines','Vice admiral','Marines','A famously powerful Marine and Luffy’s grandfather with an unconventional attitude.','Serve his own idea of justice'],
[22,'Shanks','Red-Haired','Pirate captain','Red-Haired Pirates','The captain who inspired Luffy’s dream and entrusted him with the straw hat.','See the next generation shape the era'],
[23,'Kaido','Strongest Creature','Pirate emperor','Beasts Pirates','A fearsome emperor known for extraordinary durability and a dragon form.','Create a world where the strong can live freely'],
[24,'Charlotte Linlin (Big Mom / Olin)','Big Mom','Pirate emperor','Big Mom Pirates','The ruler of Totto Land who can manipulate souls and leads a vast family.','Build a kingdom for every race'],
[25,'Marshall D. Teach','Blackbeard','Pirate emperor','Blackbeard Pirates','A calculating pirate whose ambitions make him a major force in the New World.','Claim the freedom and power he seeks'],
[26,'Silvers Rayleigh','Dark King','Former first mate','Roger Pirates','Roger’s former right-hand man, now retired, renowned for his Haki and wisdom.','Live freely after the crew’s journey'],
[27,'Kozuki Oden','Lord of Kuri','Samurai and daimyo','Kozuki Family; Whitebeard and Roger Pirates','A bold samurai whose voyages shaped his vision for Wano’s future.','Open Wano’s borders'],
[28,'Marco','Phoenix','Doctor and commander','Whitebeard Pirates','A calm veteran who can transform into a phoenix and regenerate with blue flames.','Protect the Whitebeard family'],
[29,'Benn Beckman','Red-Haired first mate','First mate','Red-Haired Pirates','Shanks’s trusted first mate, known for intelligence and composure.','Support the Red-Haired crew'],
[30,'King','King the Wildfire','All-Star','Beasts Pirates; Lunarian','A powerful Lunarian known for flame, flight and remarkable durability.','Support Kaido’s ambition'],
[31,'Charlotte Katakuri','Sweet Commander','Commander','Big Mom Pirates','A disciplined fighter with advanced Observation Haki who cares deeply for his siblings.','Protect his family'],
[32,'Sakazuki','Akainu','Fleet Admiral','Marines','A hard-line Marine leader who follows an uncompromising idea of Absolute Justice.','Enforce his view of justice'],
[33,'Borsalino','Kizaru','Admiral','Marines','An enigmatic admiral whose Devil Fruit grants light-based abilities.','Carry out Marine orders'],
[34,'Issho','Fujitora','Admiral','Marines','A blind swordsman and admiral who controls gravity and prioritises civilian safety.','Reform the world’s justice systems'],
[35,'Sengoku','Buddha','Former Fleet Admiral','Marines','A veteran strategist who can transform into a giant golden Buddha-like form.','Maintain order'],
[36,'Koby','Hero of the Marines','Marine officer','Marines; SWORD','A former cabin boy who trained hard and grew into a courageous Marine.','Become an admiral and help people'],
[37,'Kuzan','Aokiji','Former admiral','Former Marines; Blackbeard Pirates','A laid-back former admiral who can create and control ice.','Follow his own sense of justice'],
[38,'Buggy','Star Clown','Pirate captain','Cross Guild','A theatrical pirate whose public reputation often grows beyond his own plans.','Become a great pirate'],
[39,'Crocodile','Desert King','Pirate strategist','Cross Guild; formerly Baroque Works','A calculating former Warlord who controls sand and favours long-term schemes.','Gain influence and power'],
[40,'Enel','God','Former ruler','Formerly Skypiea','A self-proclaimed god with lightning powers and exceptional awareness.','Reach Fairy Vearth'],
[41,'Rob Lucci','CP0 agent','Cipher Pol agent','World Government; CP0','A highly trained government agent known for his strict loyalty to orders.','Carry out government orders'],
[42,'Gecko Moria','Shadow Master','Pirate captain','Thriller Bark Pirates','A shadow-manipulating pirate who commands a crew aboard Thriller Bark.','Build a powerful crew'],
[43,'Donquixote Doflamingo','Heavenly Demon','Pirate captain and former king','Donquixote Pirates','A manipulative former ruler who controls strings and built an underworld network.','Control the world around him'],
[44,'Dracule Mihawk','Hawk-Eyes','Master swordsman','Cross Guild; formerly Warlord','Widely recognised as the world’s greatest swordsman, he values skill and worthy rivals.','Remain at the pinnacle of swordsmanship'],
[45,'Donquixote Rosinante','Corazon','Marine undercover agent','Marines; Donquixote Family undercover','Doflamingo’s younger brother, remembered for his compassion toward Law.','Save Law from a tragic future'],
[46,'Perona','Ghost Princess','Pirate','Formerly Thriller Bark Pirates','A gothic-styled pirate who creates ghostly projections and has a dramatic personality.','Live comfortably with trusted companions'],
[47,'Shiki','Golden Lion','Pirate captain','Golden Lion Pirates','A legendary pirate from Roger’s era who can make objects and islands float.','Reshape the world through his plan'],
[48,'Zephyr','Z','Former Marine instructor','Neo Marines; Film Z','A film-original former Marine instructor whose story examines his strict ideals.','Pursue his vision of justice'],
[49,'Gild Tesoro','Gold King','Casino magnate','Gran Tesoro; Film Gold','A film-original character who controls gold and rules a vast entertainment ship.','Gain wealth and control'],
[50,'Uta','World’s Most Beloved Singer','Singer','Film Red; connected to Red-Haired Pirates','A singer whose extraordinary voice and music are central to Film Red.','Create a happier world through music'],
[51,'Kung-Fu Dugong','Kung-Fu Dugong','Martial-arts animal','Alabasta and other adventures','A seal-like animal known for martial arts and for respecting those who defeat it.','Keep training and improving']
] as const;
const characters:Character[]=rows.map(r=>({id:r[0],name:r[1],alias:r[2],role:r[3],crew:r[4],bio:r[5],goal:r[6]}));
const portrait=(id:number)=>'https://opbr-en.bn-ent.net/assets/data/webp/character/'+String(id).padStart(4,'0')+'_2d.png.webp';
const google=(name:string)=>'https://www.google.com/search?q='+encodeURIComponent(name);

export function FrameCharacterArchive(){
 const [query,setQuery]=useState('');
 const [selected,setSelected]=useState<Character|null>(null);
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return characters.filter(c=>!q||[c.name,c.alias,c.role,c.crew,c.bio].join(' ').toLowerCase().includes(q)).sort((a,b)=>a.name==='Sanji'?-1:b.name==='Sanji'?1:a.id-b.id)},[query]);
 const profiles:Record<string,{birthday:string;jp:string;en:string;age:string;height:string;fruit:string;first:string;facts:string[]}>={
 'Sanji':{birthday:'March 2',jp:'Hiroaki Hirata (adult); Ikue Ōtani (young)',en:'Eric Vale (Funimation); regional dubs vary',age:'21 after timeskip',height:'180 cm',fruit:'No confirmed Devil Fruit; kick-based Black Leg Style',first:'Episode 20 / manga chapter 43',facts:['Born Vinsmoke Sanji, third son of the Vinsmoke family.','Cook of the Straw Hat Pirates; trained by Zeff at the Baratie.','Dreams of finding the All Blue.','Keeps his hands for cooking and primarily fights with kicks.']},
 'Monkey D. Luffy':{birthday:'May 5',jp:'Mayumi Tanaka',en:'Colleen Clinkenbeard',age:'19 after timeskip',height:'174 cm',fruit:'Hito Hito no Mi, Model: Nika',first:'Episode 1 / manga chapter 1',facts:['Captain of the Straw Hat Pirates.','Shanks inspired his dream of becoming a pirate.','Wants to become King of the Pirates.']},
 'Roronoa Zoro':{birthday:'November 11',jp:'Kazuya Nakai',en:'Christopher R. Sabat',age:'21 after timeskip',height:'181 cm',fruit:'None',first:'Episode 2 / manga chapter 3',facts:['Swordsman of the Straw Hat Pirates.','Uses Three-Sword Style.','Aims to become the world’s greatest swordsman.']},
 'Nami':{birthday:'July 3',jp:'Akemi Okamura',en:'Luci Christian',age:'20 after timeskip',height:'170 cm',fruit:'None',first:'Episode 1 / manga chapter 8',facts:['Navigator of the Straw Hat Pirates.','Skilled cartographer and weather expert.','Dreams of mapping the entire world.']},
 'Usopp':{birthday:'April 1',jp:'Kappei Yamaguchi',en:'Sonny Strait',age:'19 after timeskip',height:'174 cm',fruit:'None',first:'Episode 8 / manga chapter 23',facts:['Sniper and inventive problem-solver.','Known for tall tales and improvisation.','Wants to become a brave warrior of the sea.']},
 'Tony Tony Chopper':{birthday:'December 24',jp:'Ikue Ōtani',en:'Brina Palencia',age:'17 after timeskip',height:'90 cm (standard form)',fruit:'Hito Hito no Mi',first:'Episode 81 / manga chapter 134',facts:['Reindeer and doctor of the crew.','Uses Rumble Balls for additional forms.','Dreams of curing every disease.']},
 'Nico Robin':{birthday:'February 6',jp:'Yuriko Yamaguchi',en:'Stephanie Young',age:'30 after timeskip',height:'188 cm',fruit:'Hana Hana no Mi',first:'Episode 67 / manga chapter 114',facts:['Archaeologist of the Straw Hat Pirates.','Can read Poneglyphs.','Seeks the true history of the world.']},
 'Franky':{birthday:'March 9',jp:'Kazuki Yao; Subaru Kimura in later episodes',en:'Patrick Seitz',age:'36 after timeskip',height:'240 cm',fruit:'None',first:'Episode 233 / manga chapter 329',facts:['Cyborg shipwright.','Built the Thousand Sunny.','Wants his ship to sail around the world.']},
 'Brook':{birthday:'April 3',jp:'Chō',en:'Ian Sinclair',age:'90 after timeskip',height:'277 cm',fruit:'Yomi Yomi no Mi',first:'Episode 337 / manga chapter 442',facts:['Musician and swordsman.','A living skeleton revived by his Devil Fruit.','Promises to reunite with Laboon.']},
 'Jinbe':{birthday:'April 2',jp:'Katsuhisa Hōki',en:'Daniel Baugh',age:'46 after timeskip',height:'301 cm',fruit:'None',first:'Episode 430 / manga chapter 528',facts:['Helmsman of the Straw Hat Pirates.','Master of Fish-Man Karate.','Former Warlord of the Sea.']},
 'Portgas D. Ace':{birthday:'January 1',jp:'Toshio Furukawa',en:'Travis Willingham',age:'20 at death',height:'185 cm',fruit:'Mera Mera no Mi (formerly)',first:'Episode 91 / manga chapter 154',facts:['Luffy’s sworn older brother.','Former commander of the Whitebeard Pirates.','Known as Fire Fist Ace.']},
 'Trafalgar D. Water Law':{birthday:'October 6',jp:'Hiroshi Kamiya',en:'Matthew Mercer',age:'26 after timeskip',height:'191 cm',fruit:'Ope Ope no Mi',first:'Episode 392 / manga chapter 498',facts:['Captain and doctor of the Heart Pirates.','Known as the Surgeon of Death.','Uses ROOM for spatial operations.']},
 'Shanks':{birthday:'March 9',jp:'Shūichi Ikeda',en:'Brandon Potter',age:'39',height:'199 cm',fruit:'None confirmed',first:'Episode 4 / manga chapter 1',facts:['Captain of the Red-Haired Pirates.','Inspired Luffy and entrusted him with his straw hat.','One of the Four Emperors.']},
 'Gol D. Roger':{birthday:'December 31',jp:'Chikao Ōtsuka; Masane Tsukayama in later portrayal',en:'Sean Hennigan',age:'53 at death',height:'274 cm',fruit:'None confirmed',first:'Episode 48 / manga chapter 96',facts:['Known as the Pirate King.','Reached the final island with his crew.','His execution began the Great Pirate Era.']},
 'Boa Hancock':{birthday:'September 2',jp:'Kotono Mitsuishi',en:'Lydia Mackay',age:'31 after timeskip',height:'191 cm',fruit:'Mero Mero no Mi',first:'Episode 409 / manga chapter 516',facts:['Empress of Amazon Lily.','Former Warlord of the Sea.','Known as the Pirate Empress.']},
 'Buggy':{birthday:'August 8',jp:'Shigeru Chiba',en:'Mike McFarland',age:'39',height:'192 cm',fruit:'Bara Bara no Mi',first:'Episode 4 / manga chapter 9',facts:['Flamboyant pirate with a long history around Shanks.','Associated with Cross Guild.','His reputation often exceeds his plans.']},
 'Dracule Mihawk':{birthday:'March 9',jp:'Hirohiko Kakegawa',en:'John Gremillion',age:'43',height:'198 cm',fruit:'None',first:'Episode 23 / manga chapter 49',facts:['Known as Hawk-Eyes.','Recognised as the world’s greatest swordsman.','A former Warlord of the Sea.']},
 'Koby':{birthday:'May 13',jp:'Mika Doi',en:'Micah Solusod',age:'18',height:'167 cm',fruit:'None',first:'Episode 1 / manga chapter 2',facts:['Started as a captive cabin boy.','Trained under Garp.','Aspires to become a great Marine.']},
 'Sakazuki':{birthday:'August 16',jp:'Fumihiko Tachiki',en:'Andrew Love',age:'55',height:'306 cm',fruit:'Magu Magu no Mi',first:'Episode 278 / manga chapter 397',facts:['Known as Akainu.','Fleet Admiral of the Marines.','Follows an uncompromising view of justice.']},
 'Borsalino':{birthday:'November 23',jp:'Ryōtarō Okiayu',en:'Ray Hurd',age:'58',height:'302 cm',fruit:'Pika Pika no Mi',first:'Episode 398 / manga chapter 504',facts:['Known as Kizaru.','Marine admiral.','Has light-based powers.']},
 'Kuzan':{birthday:'September 21',jp:'Takehito Koyasu',en:'Jason Douglas',age:'49',height:'298 cm',fruit:'Hie Hie no Mi',first:'Episode 225 / manga chapter 303',facts:['Known as Aokiji.','Former Marine admiral.','Can create and control ice.']},
 'Enel':{birthday:'May 6',jp:'Tōru Ōkawa',en:'J. Michael Tatum',age:'39',height:'266 cm',fruit:'Goro Goro no Mi',first:'Episode 167 / manga chapter 254',facts:['Former ruler of Skypiea.','Can generate and control lightning.','Intended to reach Fairy Vearth.']},
 'Donquixote Doflamingo':{birthday:'October 23',jp:'Hideyuki Tanaka',en:'Robert McCollum',age:'41',height:'305 cm',fruit:'Ito Ito no Mi',first:'Episode 151 / manga chapter 233',facts:['Former king of Dressrosa.','Known as the Heavenly Demon.','Operated a major underworld network.']},
 'Rob Lucci':{birthday:'June 2',jp:'Tomokazu Seki',en:'Jason Liebrecht',age:'30',height:'212 cm',fruit:'Neko Neko no Mi, Model: Leopard',first:'Episode 243 / manga chapter 323',facts:['Highly trained Cipher Pol agent.','Known for Rokushiki techniques.','Later associated with CP0.']}
 };
 const openProfile=(c:Character)=>setSelected(c);
 return <section className="frame-character-archive">
  <div className="frame-character-head"><div><small>CHARACTER ARCHIVE</small><h3><Users size={18}/> One Piece characters</h3><p>Swipe sideways to browse · tap any card for the full profile</p></div><span className="frame-character-count">{visible.length} / {characters.length}</span></div>
  <label className="frame-character-search"><Search size={16}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names, crews, roles…" aria-label="Search One Piece characters"/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Clear character search"><X size={15}/></button>}</label>
  <div className="frame-character-rail" aria-label="Horizontally scrolling One Piece character profiles">{visible.map(c=><article className={'frame-character-card'+(c.name==='Sanji'?' sanji-featured':'')} key={c.id} role="button" tabIndex={0} onClick={()=>openProfile(c)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProfile(c)}}} aria-label={'Open details for '+c.name}>
   <div className="frame-character-portrait"><img src={portrait(c.id)} alt={c.name} loading={c.name==='Sanji'?'eager':'lazy'} onError={e=>{e.currentTarget.style.visibility='hidden';e.currentTarget.parentElement?.classList.add('portrait-unavailable')}}/><span className="frame-character-open"><Users size={13}/> View profile</span></div>
   <div className="frame-character-copy"><a className="frame-character-name" href={google(c.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{c.name}<ExternalLink size={13}/></a><span className="frame-character-alias">{c.alias}</span><div className="frame-character-role">{c.role}</div><p>{c.bio}</p><span className="frame-character-tap">Tap card for facts <span>↗</span></span></div>
  </article>)}</div><div className="frame-character-rail-hint"><span>← Swipe to explore →</span><span>{visible.length} profiles</span></div>
  <p className="frame-character-source">Portraits are linked from ONE PIECE Bounty Rush. Japanese and English cast fields identify common anime dub credits where available; other regional dubs may differ. Unknown values are labelled rather than guessed.</p>
  {selected&&<div className="frame-character-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="frame-character-modal" role="dialog" aria-modal="true" aria-label={selected.name+' character details'}>
   <button className="frame-character-modal-close" type="button" onClick={()=>setSelected(null)} aria-label="Close character details"><X size={19}/></button>
   <div className="frame-character-modal-hero"><img src={portrait(selected.id)} alt={selected.name} onError={e=>{e.currentTarget.style.visibility='hidden'}}/><div><small>ONE PIECE · CHARACTER FILE</small><h2>{selected.name}</h2><p>{selected.alias} · {selected.role}</p><span className="frame-character-modal-affiliation">{selected.crew}</span><a className="frame-character-google" href={google(selected.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Search exact character name on Google <ExternalLink size={13}/></a></div></div>
   <div className="frame-character-fact-grid"><div><span><CalendarDays size={14}/> Birthday</span><b>{profiles[selected.name]?.birthday||'Not verified in this profile'}</b></div><div><span>Age</span><b>{profiles[selected.name]?.age||'Not verified / depends on story period'}</b></div><div><span>Height</span><b>{profiles[selected.name]?.height||'Not verified in this profile'}</b></div><div><span><Mic2 size={14}/> Japanese voice actor</span><b>{profiles[selected.name]?.jp||'Not yet verified for this profile'}</b></div><div><span><Mic2 size={14}/> English voice actor</span><b>{profiles[selected.name]?.en||'Dub-dependent / not yet verified'}</b></div><div><span>Devil Fruit / ability</span><b>{profiles[selected.name]?.fruit||'See character description; details not verified here'}</b></div><div><span>First appearance</span><b>{profiles[selected.name]?.first||'Not yet verified in this profile'}</b></div><div><span>Affiliation</span><b>{selected.crew}</b></div></div>
   <section className="frame-character-modal-section"><h3>About</h3><p>{selected.bio}</p><p><strong>Goal / dream:</strong> {selected.goal}</p><p><strong>Role:</strong> {selected.role}. <strong>Alias:</strong> {selected.alias}.</p></section>
   <section className="frame-character-modal-section"><h3>Facts</h3><ul>{(profiles[selected.name]?.facts||[selected.bio,'Affiliation: '+selected.crew,'Goal / dream: '+selected.goal]).map((fact,i)=><li key={i}>{fact}</li>)}</ul></section>
   <div className="frame-character-modal-footer"><span>Facts can vary by timeskip and dub. Missing data is marked instead of invented.</span><button type="button" onClick={()=>setSelected(null)}>Done</button></div>
  </section></div>}
 </section>
}
