import {useEffect,useMemo,useState} from 'react';
import {ExternalLink,Search,Users,X,CalendarDays,Mic2} from 'lucide-react';

type Character={id:number;name:string;alias:string;role:string;crew:string;bio:string;goal:string};
const characters:Character[]=[];
const google=(name:string)=>'https://www.google.com/search?q='+encodeURIComponent(name);

export function FrameCharacterArchive(){
 const [query,setQuery]=useState('');
 const [selected,setSelected]=useState<Character|null>(null);
 const [portraits,setPortraits]=useState<Record<string,string>>({});
 useEffect(()=>{
  let active=true;
  const load=async()=>{
   const titles=characters.map(c=>c.name==='Charlotte Linlin (Big Mom / Olin)'?'Charlotte Linlin':c.name==='Trafalgar D. Water Law'?'Trafalgar D. Water Law':c.name);
   const found:Record<string,string>={};
   for(let i=0;i<titles.length;i+=40){
    const batch=titles.slice(i,i+40);
    try{
     const url='https://onepiece.fandom.com/api.php?action=query&format=json&origin=*&redirects=1&prop=pageimages&piprop=thumbnail& pithumbsize=480&titles='+encodeURIComponent(batch.join('|')).replace(/%20/g,'%20');
     const response=await fetch(url.replace('& pithumbsize','&pithumbsize'));
     if(!response.ok)continue;
     const data=await response.json();
     for(const page of Object.values(data?.query?.pages||{}) as any[]){
      const title=String(page.title||'');const source=page.thumbnail?.source;
      if(source){const character=characters.find(c=>c.name.toLowerCase()===title.toLowerCase()||(c.name==='Charlotte Linlin (Big Mom / Olin)'&&title.toLowerCase()==='charlotte linlin'));
       if(character)found[character.name]=source;
      }
     }
    }catch{}
   }
   if(active)setPortraits(found);
  };
  void load();
  return()=>{active=false};
 },[]);


 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return characters.filter(c=>!q||[c.name,c.alias,c.role,c.crew,c.bio].join(' ').toLowerCase().includes(q)).sort((a,b)=>{const ai=popularityOrder.indexOf(a.name as typeof popularityOrder[number]),bi=popularityOrder.indexOf(b.name as typeof popularityOrder[number]);if(ai!==-1||bi!==-1)return (ai===-1?999:ai)-(bi===-1?999:bi);return a.id-b.id})},[query]);
 const displayRank=(name:string)=>{const rank=popularityOrder.indexOf(name as typeof popularityOrder[number]);return rank===-1?null:rank+1};
 const profiles:Record<string,{birthday:string;jp:string;en:string;age:string;height:string;fruit:string;first:string;facts:string[]}>={
 'Sanji':{birthday:'March 2',jp:'Hiroaki Hirata (adult); Ikue Ōtani (young)',en:'Eric Vale (Funimation); regional dubs vary',age:'21 after timeskip',height:'180 cm',fruit:'No confirmed Devil Fruit; kick-based Black Leg Style',first:'Episode 20 / manga chapter 43',facts:['Born Vinsmoke Sanji, third son of the Vinsmoke family.','Cook of the Straw Hat Pirates; trained by Zeff at the Baratie.','Dreams of finding the All Blue.','Keeps his hands for cooking and primarily fights with kicks.']},
 'Monkey D. Luffy':{birthday:'May 5',jp:'Mayumi Tanaka',en:'Colleen Clinkenbeard',age:'19 after timeskip',height:'174 cm',fruit:'Hito Hito no Mi, Model: Nika',first:'Episode 1 / manga chapter 1',facts:['Captain of the Straw Hat Pirates.','Shanks inspired his dream of becoming a pirate.','Wants to become King of the Pirates.']},
 'Roronoa Zoro':{birthday:'November 11',jp:'Kazuya Nakai',en:'Christopher R. Sabat',age:'21 after timeskip',height:'181 cm',fruit:'None',first:'Episode 2 / manga chapter 3',facts:['Swordsman of the Straw Hat Pirates.','Uses Three-Sword Style.','Aims to become the world’s greatest swordsman.']},
 'Nami':{birthday:'July 3',jp:'Akemi Okamura',en:'Luci Christian',age:'20 after timeskip',height:'170 cm',fruit:'None',first:'Episode 1 / manga chapter 8',facts:['Navigator of the Straw Hat Pirates.','Skilled cartographer and weather expert.','Dreams of mapping the entire world.']},
 'Usopp':{birthday:'April 1',jp:'Kappei Yamaguchi',en:'Sonny Strait',age:'19 after timeskip',height:'174 cm',fruit:'None',first:'Episode 8 / manga chapter 23',facts:['Sniper and inventive problem-solver.','Known for tall tales and improvisation.','Wants to become a brave warrior of the sea.']},
 'Tony Tony Chopper':{birthday:'December 24',jp:'Ikue Ōtani',en:'Brina Palencia',age:'17 after timeskip',height:'90 cm (standard form)',fruit:'Hito Hito no Mi',first:'Episode 81 / manga chapter 134',facts:['Reindeer and doctor of the crew.','Uses Rumble Balls for additional forms.','Dreams of curing every disease.']},
 'Nico Robin':{birthday:'February 6',jp:'Yuriko Yamaguchi',en:'Stephanie Young',age:'30 after timeskip',height:'188 cm',fruit:'Hana Hana no Mi',first:'Episode 67 / manga chapter 114',facts:['Archaeologist of the Straw Hat Pirates.','Can read Poneglyphs.','Seeks the true history of the world.']},
 'Franky':{birthday:'March 9',jp:'Kazuki Yao; Subaru Kimura in later episodes',en:'Patrick Seitz',age:'36 after timeskip',height:'240 cm',fruit:'None',first:'Episode 233 / manga chapter 329',facts:['Cyborg shipwright.','Built the Thousand Sunny.','Wants his ship to sail around the world.']},
 'Brook':{birthday:'April 3',jp:'Chō',en:'Ian Sinclair',age:'90 after timeskip',height:'277 cm',fruit:'Yomi Yomi no Mi',first:'Episode 337 / manga chapter 442',facts:['Musician and swordsman.','A living skeleton revived by his Devil Fruit.','Promises to reunite with Laboon.']},
 'Jinbe':{birthday:'April 2',jp:'Katsuhisa Hōki',en:'Daniel Baugh',age:'46 after timeskip',height:'301 cm',fruit:'None',first:'Episode 430 / manga chapter 528',facts:['Helmsman of the Straw Hat Pirates.','Master of Fish-Man Karate.','Former Warlord of the Sea.']},
 'Portgas D. Ace':{birthday:'January 1',jp:'Toshio Furukawa',en:'Travis Willingham',age:'20 at death',height:'185 cm',fruit:'Mera Mera no Mi (formerly)',first:'Episode 91 / manga chapter 154',facts:['Luffy’s sworn older brother.','Former commander of the Whitebeard Pirates.','Known as Fire Fist Ace.']},
 'Trafalgar D. Water Law':{birthday:'October 6',jp:'Hiroshi Kamiya',en:'Matthew Mercer',age:'26 after timeskip',height:'191 cm',fruit:'Ope Ope no Mi',first:'Episode 392 / manga chapter 498',facts:['Captain and doctor of the Heart Pirates.','Known as the Surgeon of Death.','Uses ROOM for spatial operations.']},
 'Shanks':{birthday:'March 9',jp:'Shūichi Ikeda',en:'Brandon Potter',age:'39',height:'199 cm',fruit:'None confirmed',first:'Episode 4 / manga chapter 1',facts:['Captain of the Red-Haired Pirates.','Inspired Luffy and entrusted him with his straw hat.','One of the Four Emperors.']},
 'Gol D. Roger':{birthday:'December 31',jp:'Chikao Ōtsuka; Masane Tsukayama in later portrayal',en:'Sean Hennigan',age:'53 at death',height:'274 cm',fruit:'None confirmed',first:'Episode 48 / manga chapter 96',facts:['Known as the Pirate King.','Reached the final island with his crew.','His execution began the Great Pirate Era.']},
 'Boa Hancock':{birthday:'September 2',jp:'Kotono Mitsuishi',en:'Lydia Mackay',age:'31 after timeskip',height:'191 cm',fruit:'Mero Mero no Mi',first:'Episode 409 / manga chapter 516',facts:['Empress of Amazon Lily.','Former Warlord of the Sea.','Known as the Pirate Empress.']},
 'Buggy':{birthday:'August 8',jp:'Shigeru Chiba',en:'Mike McFarland',age:'39',height:'192 cm',fruit:'Bara Bara no Mi',first:'Episode 4 / manga chapter 9',facts:['Flamboyant pirate with a long history around Shanks.','Associated with Cross Guild.','His reputation often exceeds his plans.']},
 'Dracule Mihawk':{birthday:'March 9',jp:'Hirohiko Kakegawa',en:'John Gremillion',age:'43',height:'198 cm',fruit:'None',first:'Episode 23 / manga chapter 49',facts:['Known as Hawk-Eyes.','Recognised as the world’s greatest swordsman.','A former Warlord of the Sea.']},
 'Koby':{birthday:'May 13',jp:'Mika Doi',en:'Micah Solusod',age:'18',height:'167 cm',fruit:'None',first:'Episode 1 / manga chapter 2',facts:['Started as a captive cabin boy.','Trained under Garp.','Aspires to become a great Marine.']},
 'Sakazuki':{birthday:'August 16',jp:'Fumihiko Tachiki',en:'Andrew Love',age:'55',height:'306 cm',fruit:'Magu Magu no Mi',first:'Episode 278 / manga chapter 397',facts:['Known as Akainu.','Fleet Admiral of the Marines.','Follows an uncompromising view of justice.']},
 'Borsalino':{birthday:'November 23',jp:'Ryōtarō Okiayu',en:'Ray Hurd',age:'58',height:'302 cm',fruit:'Pika Pika no Mi',first:'Episode 398 / manga chapter 504',facts:['Known as Kizaru.','Marine admiral.','Has light-based powers.']},
 'Kuzan':{birthday:'September 21',jp:'Takehito Koyasu',en:'Jason Douglas',age:'49',height:'298 cm',fruit:'Hie Hie no Mi',first:'Episode 225 / manga chapter 303',facts:['Known as Aokiji.','Former Marine admiral.','Can create and control ice.']},
 'Enel':{birthday:'May 6',jp:'Tōru Ōkawa',en:'J. Michael Tatum',age:'39',height:'266 cm',fruit:'Goro Goro no Mi',first:'Episode 167 / manga chapter 254',facts:['Former ruler of Skypiea.','Can generate and control lightning.','Intended to reach Fairy Vearth.']},
 'Donquixote Doflamingo':{birthday:'October 23',jp:'Hideyuki Tanaka',en:'Robert McCollum',age:'41',height:'305 cm',fruit:'Ito Ito no Mi',first:'Episode 151 / manga chapter 233',facts:['Former king of Dressrosa.','Known as the Heavenly Demon.','Operated a major underworld network.']},
 'Rob Lucci':{birthday:'June 2',jp:'Tomokazu Seki',en:'Jason Liebrecht',age:'30',height:'212 cm',fruit:'Neko Neko no Mi, Model: Leopard',first:'Episode 243 / manga chapter 323',facts:['Highly trained Cipher Pol agent.','Known for Rokushiki techniques.','Later associated with CP0.']} ,
 'Loki':{birthday:'Not officially confirmed',jp:'Yūichi Nakamura',en:'Not confirmed here',age:'63 (reported)',height:'Giant; exact value not confirmed here',fruit:'Legendary Devil Fruit associated with Elbaph; details treated cautiously',first:'Manga chapter 1130',facts:['Prince of Elbaph and son of King Harald.','Known as the Accursed Prince.','Has long admired Rocks D. Xebec.']},
 'Rocks D. Xebec':{birthday:'Not officially confirmed',jp:'Shinshū Fuji (anime credit)',en:'Paul St. Peter (Funimation credit)',age:'43, 38 years before the current story (reported)',height:'Not confirmed here',fruit:'No confirmed Devil Fruit entry',first:'Manga chapter 957 / anime episode 958',facts:['Captain of the Rocks Pirates.','His crew included future legends such as Whitebeard, Big Mom, Kaido and Shiki.','Sought to become King of the World.','His defeat is tied to the God Valley Incident.']},
 'Joy Boy':{birthday:'Unknown',jp:'Urara Takano (credited portrayal)',en:'Erica Schroeder (Funimation credit)',age:'Ancient figure; exact age uncertain',height:'Unknown',fruit:'Associated with Hito Hito no Mi, Model: Nika in story lore',first:'Void Century; later silhouette in the anime',facts:['Lived around 900 years ago.','Associated with the ancient kingdom and a promise to Fish-Man Island.','Left a treasure at the final island according to the story.']},
 'King Harald':{birthday:'Not confirmed',jp:'Not confirmed here',en:'Not confirmed here',age:'Not confirmed',height:'Giant',fruit:'Not confirmed',first:'Elbaph flashback material',facts:['Former king of Elbaph.','Father of Loki.','His relationship with Rocks shaped Elbaph’s history.']},
 'Imu':{birthday:'Unknown',jp:'Not confirmed here',en:'Not confirmed here',age:'Unknown',height:'Unknown',fruit:'Unknown',first:'Manga chapter 906 / anime episode 885',facts:['Secretive ruler at the top of the World Government.','Connected to mysteries surrounding the Void Century.','Many details remain deliberately unrevealed.']},
 'Davy D. Jones':{birthday:'Unknown',jp:'Not confirmed',en:'Not confirmed',age:'Legendary historical figure',height:'Unknown',fruit:'Unknown',first:'Mentioned in lore',facts:['Legendary name tied to Davy family lore.','Connection to Rocks is surrounded by mystery.','Details are not fully confirmed.']},
 'Figarland Garling':{birthday:'Not confirmed',jp:'Not confirmed here',en:'Not confirmed here',age:'Unknown',height:'Unknown',fruit:'Not confirmed',first:'Manga chapter 1086',facts:['Associated with the God’s Knights.','A key figure in the Figarland family.','Connected to God Valley events.']},
 'Scopper Gaban':{birthday:'Not confirmed here',jp:'Not confirmed here',en:'Not confirmed here',age:'Unknown',height:'Unknown',fruit:'Not confirmed',first:'Roger Pirates story material',facts:['Veteran of the Roger Pirates.','One of the notable members of Roger’s crew.','Helped the crew on its legendary voyage.']},
 'Captain John':{birthday:'Unknown',jp:'Not confirmed',en:'Not confirmed',age:'Unknown',height:'Unknown',fruit:'Unknown',first:'Thriller Bark references',facts:['Former member of the Rocks Pirates.','Known for a legendary treasure.','Personal details remain limited.']},
 'Ochoku':{birthday:'Unknown',jp:'Not confirmed',en:'Not confirmed',age:'Unknown',height:'Unknown',fruit:'Unknown',first:'Manga backstory references',facts:['Also known as Wang Zhi.','Associated with the Rocks Pirates.','Linked to the history of Hachinosu.']},
 'Buckingham Stussy':{birthday:'Not confirmed',jp:'Not confirmed here',en:'Not confirmed here',age:'Unknown',height:'Unknown',fruit:'Not confirmed',first:'Modern identity revealed in manga',facts:['Former member of the Rocks Pirates.','Connected to MADS and the underworld.','Distinct from the clone known as Stussy.']},
 'Gloriosa':{birthday:'Not confirmed here',jp:'Ako Mayama (reported)',en:'Not confirmed here',age:'Elder',height:'Unknown',fruit:'Not confirmed',first:'Amazon Lily flashback',facts:['Also called Elder Nyon.','Former empress of Amazon Lily.','Lived through the era of the Rocks Pirates.']},
 'Streusen':{birthday:'Not confirmed here',jp:'Haruhiko Jō (reported)',en:'Not confirmed here',age:'Unknown',height:'Unknown',fruit:'Kuku Kuku no Mi',first:'Whole Cake Island story',facts:['Chef and longtime associate of Big Mom.','Associated with the early history of her crew.','His Devil Fruit can turn objects into food.']},
 'Kong':{birthday:'Unknown',jp:'Not confirmed',en:'Not confirmed',age:'Unknown',height:'Unknown',fruit:'Not confirmed',first:'Marineford-era story material',facts:['Former Fleet Admiral.','Later Commander-in-Chief of the World Government’s armed forces.','A senior figure in the military structure.']},
 'Shimotsuki Ryuma':{birthday:'Not confirmed here',jp:'Not confirmed here',en:'Not confirmed here',age:'Historical figure',height:'Unknown',fruit:'None confirmed',first:'Thriller Bark / Monsters',facts:['Legendary samurai from Wano.','Remembered as a national hero.','Associated with the title Sword God.']},
 'Fisher Tiger':{birthday:'November 5 (commonly listed)',jp:'Kōji Ishii (reported)',en:'Not confirmed here',age:'Deceased',height:'Unknown',fruit:'None confirmed',first:'Fish-Man Island flashback',facts:['Founded the Sun Pirates.','Fought against slavery and oppression.','Inspired later generations.']},
 'Kozuki Toki':{birthday:'Not confirmed here',jp:'Keiko Han (reported)',en:'Not confirmed here',age:'Deceased; born centuries earlier',height:'Unknown',fruit:'Toki Toki no Mi',first:'Wano backstory',facts:['Born in the distant past.','Could send herself and others forward through time.','Her actions helped shape Wano’s future.']},
 'Nefertari D. Lily':{birthday:'Unknown',jp:'Not confirmed',en:'Not confirmed',age:'Historical figure',height:'Unknown',fruit:'Unknown',first:'Void Century revelations',facts:['Ancient queen of Alabasta.','Connected to the mystery of the Poneglyphs.','Her full history remains incompletely revealed.']},
 'Nika':{birthday:'Unknown; mythic figure',jp:'Not confirmed as a separate character voice',en:'Not confirmed',age:'Legendary',height:'Unknown',fruit:'Legend associated with the Hito Hito no Mi, Model: Nika',first:'Ancient lore references',facts:['Known as the Sun God in legend.','Symbolises liberation and joy.','Central to the meaning of Luffy’s awakened power.']},
 'Zunesha':{birthday:'Unknown',jp:'Not confirmed here',en:'Not confirmed here',age:'Ancient; exact age unknown',height:'Enormous; exact height not confirmed',fruit:'None confirmed',first:'Zou arc',facts:['Ancient elephant that carries Zou on its back.','Bound to continue walking as punishment.','Has a mysterious connection to Joy Boy.']},
 'Neptune':{birthday:'Not confirmed here',jp:'Minoru Inaba (reported)',en:'Not confirmed here',age:'Unknown',height:'Very large; exact value not listed',fruit:'None confirmed',first:'Fish-Man Island arc',facts:['King of the Ryugu Kingdom.','Father of Shirahoshi.','Connected to the promise left by Joy Boy.']}
 };
 const openProfile=(c:Character)=>setSelected(c);
 return <section className="frame-character-archive">
  <div className="frame-character-head"><div><small>CHARACTER ARCHIVE</small><h3><Users size={18}/> One Piece characters</h3><p>Swipe sideways to browse · tap any card for the full profile</p></div><span className="frame-character-count">{visible.length} / {characters.length}</span></div>
  <label className="frame-character-search"><Search size={16}/><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search names, crews, roles…" aria-label="Search One Piece characters"/>{query&&<button type="button" onClick={()=>setQuery('')} aria-label="Clear character search"><X size={15}/></button>}</label>
  <div className="frame-character-rail" aria-label="Horizontally scrolling One Piece character profiles">{visible.map(c=><article className={'frame-character-card'+(c.name==='Sanji'?' sanji-featured':'')} key={c.id} role="button" tabIndex={0} onClick={()=>openProfile(c)} onKeyDown={e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openProfile(c)}}} aria-label={'Open details for '+c.name}>
   <div className="frame-character-portrait"><CharacterPortrait name={c.name} image={portraits[c.name]}/><span style={{position:'absolute',top:8,left:8,zIndex:2,padding:'4px 8px',borderRadius:999,background:'rgba(10,15,28,.86)',color:'#fff',fontSize:12,fontWeight:800,border:'1px solid rgba(255,255,255,.25)'}}>{displayRank(c.name)===null?'Unranked':'#'+displayRank(c.name)}</span><span className="frame-character-open"><Users size={13}/> View profile</span></div>
   <div className="frame-character-copy"><a className="frame-character-name" href={google(c.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>{c.name}<ExternalLink size={13}/></a><span className="frame-character-alias">{c.alias}</span><div className="frame-character-role">{c.role}</div><p>{c.bio}</p><span className="frame-character-tap">Tap card for facts <span>↗</span></span></div>
  </article>)}</div><div className="frame-character-rail-hint"><span>← Swipe to explore →</span><span>{visible.length} profiles</span></div>
  <p className="frame-character-source">Character portraits are loaded from matching One Piece Wiki character pages; unavailable images fall back to initials rather than showing another character. Japanese and English cast fields identify common anime dub credits where available; other regional dubs may differ. Unknown values are labelled rather than guessed.</p>
  {selected&&<div className="frame-character-modal-backdrop" role="presentation" onMouseDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><section className="frame-character-modal" role="dialog" aria-modal="true" aria-label={selected.name+' character details'}>
   <button className="frame-character-modal-close" type="button" onClick={()=>setSelected(null)} aria-label="Close character details"><X size={19}/></button>
   <div className="frame-character-modal-hero"><CharacterPortrait name={selected.name} image={portraits[selected.name]} large/><div><small>ONE PIECE · CHARACTER FILE · {displayRank(selected.name)===null?'UNRANKED':'CUSTOM RANK #'+displayRank(selected.name)}</small><h2>{selected.name}</h2><p>{selected.alias} · {selected.role}</p><span className="frame-character-modal-affiliation">{selected.crew}</span><a className="frame-character-google" href={google(selected.name)} target="_blank" rel="noreferrer" onClick={e=>e.stopPropagation()}>Search exact character name on Google <ExternalLink size={13}/></a></div></div>
   <div className="frame-character-fact-grid"><div><span><CalendarDays size={14}/> Birthday</span><b>{profiles[selected.name]?.birthday||'Not verified in this profile'}</b></div><div><span>Age</span><b>{profiles[selected.name]?.age||'Not verified / depends on story period'}</b></div><div><span>Height</span><b>{profiles[selected.name]?.height||'Not verified in this profile'}</b></div><div><span><Mic2 size={14}/> Japanese voice actor</span><b>{profiles[selected.name]?.jp||'Not yet verified for this profile'}</b></div><div><span><Mic2 size={14}/> English voice actor</span><b>{profiles[selected.name]?.en||'Dub-dependent / not yet verified'}</b></div><div><span>Devil Fruit / ability</span><b>{profiles[selected.name]?.fruit||'See character description; details not verified here'}</b></div><div><span>First appearance</span><b>{profiles[selected.name]?.first||'Not yet verified in this profile'}</b></div><div><span>Affiliation</span><b>{selected.crew}</b></div></div>
   <section className="frame-character-modal-section"><h3>About</h3><p>{selected.bio}</p><p><strong>Goal / dream:</strong> {selected.goal}</p><p><strong>Role:</strong> {selected.role}. <strong>Alias:</strong> {selected.alias}.</p></section>
   <section className="frame-character-modal-section"><h3>Facts</h3><ul>{(profiles[selected.name]?.facts||[selected.bio,'Affiliation: '+selected.crew,'Goal / dream: '+selected.goal]).map((fact,i)=><li key={i}>{fact}</li>)}</ul></section>
   <div className="frame-character-modal-footer"><span>Facts can vary by timeskip and dub. Missing data is marked instead of invented.</span><button type="button" onClick={()=>setSelected(null)}>Done</button></div>
  </section></div>}
 </section>
}
