import {useState} from 'react';
import {Check,ExternalLink,Heart,Star,X} from 'lucide-react';
import type {MediaItem,Status} from '../types';

const labels:Record<Status,string>={watching:'Watching',reading:'Reading',playing:'Playing',completed:'Completed',planned:'Planned',paused:'Paused',dropped:'Dropped'};
const units={anime:'episodes',manga:'chapters',manhwa:'chapters','light-novel':'chapters','visual-novel':'%',movie:'watch state',series:'episodes',game:'%',book:'pages'} as const;
const types:Record<MediaItem['medium'],string>={anime:'Anime',manga:'Manga',manhwa:'Manhwa','light-novel':'Light Novel','visual-novel':'Visual Novel',movie:'Movie',series:'Series',game:'Game',book:'Book'};
const links=(m:MediaItem)=>{const q=encodeURIComponent(m.title);return [
 m.anilistId?{label:'AniList',url:'https://anilist.co/'+(['manga','manhwa','light-novel'].includes(m.medium)?'manga':'anime')+'/'+m.anilistId}:null,
 m.game?.storeUrl?{label:'Steam',url:m.game.storeUrl}:null,
 {label:'IMDb',url:'https://www.imdb.com/find/?q='+q},{label:'JustWatch',url:'https://www.justwatch.com/in/search?q='+q},{label:'Google',url:'https://www.google.com/search?q='+q+' official watch buy'}
 ].filter(Boolean) as {label:string;url:string}[]};

export function FrameDetail({item,library,close,save}:{item:MediaItem;library:MediaItem[];close:()=>void;save:(x:MediaItem)=>void}){
 const [d,setD]=useState(item),[note,setNote]=useState(item.notes||'');
 const game=d.medium==='game',max=game?100:(d.total||500),pct=game?d.progress:(d.progress/(d.total||1)*100);
 const progress=(n:number)=>setD(game?{...d,progress:n,game:d.game?{...d.game,storyProgress:n}:undefined}:{...d,progress:Math.max(0,Math.min(max,n))});
 const setTotal=(value:number)=>{const n=Math.max(1,Math.min(2000,value||1));setD({...d,total:n,customTotal:n,progress:Math.min(d.progress,n)})};
 return <div className="overlay"><aside className="detail-drawer"><button className="close-btn" onClick={close}><X/></button><div className="detail-cover"><img src={d.backdrop||d.poster} alt=""/><div/></div><div className="detail-body"><img className="detail-poster" src={d.poster} alt=""/><div className="detail-main"><small>{types[d.medium]} · {labels[d.status]}</small><h2>{d.title}</h2><div className="detail-rating"><span><Star size={13} fill="currentColor"/> Source {d.score==null?'—':d.score.toFixed(1)}</span><span>Your {d.personalRating==null?'—':d.personalRating.toFixed(1)}</span></div><p>{d.description||'No description available.'}</p><div className="tags">{d.genres.slice(0,8).map(x=><span key={x}>{x}</span>)}</div></div></div>
 <section className="detail-section"><div className="detail-section-head"><h3>Progress</h3><span>{Math.round(pct)}%</span></div><input className="progress-slider" type="range" min="0" max={max} value={d.progress} onChange={e=>progress(Number(e.target.value))}/><div className="progress-edit"><input type="number" min="0" max={max} value={d.progress} onChange={e=>progress(Number(e.target.value)||0)}/><span>{d.progressUnit||units[d.medium]}</span><span>/</span><input type="number" min="1" max="2000" value={d.total||500} onChange={e=>setTotal(Number(e.target.value))}/><span>total</span></div><small className="hint">External totals are defaults, not rules. Change the total for different editions or inaccurate source data.</small></section>
 <section className="detail-section two-col"><label>Status<select value={d.status} onChange={e=>setD({...d,status:e.target.value as Status})}>{Object.entries(labels).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Your rating<input type="number" min="0" max="10" step=".1" value={d.personalRating??''} onChange={e=>setD({...d,personalRating:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>Parent entry<select value={d.parentId||''} onChange={e=>setD({...d,parentId:e.target.value||undefined})}><option value="">None</option>{library.filter(x=>x.id!==d.id).map(x=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label><label>Custom total<input type="number" min="1" max="2000" value={d.total||500} onChange={e=>setTotal(Number(e.target.value))}/></label></section>
 {d.game&&<section className="detail-section game-box"><h3>Game information</h3><div><span>Developer</span><b>{d.game.developer||'—'}</b></div><div><span>Publisher</span><b>{d.game.publisher||'—'}</b></div><div><span>Platforms</span><b>{d.game.platforms?.join(', ')||'—'}</b></div><div><span>Availability</span><b>{d.game.isFree?'Free':d.game.priceText||'Check store'}</b></div></section>}
 <section className="detail-section"><h3>Where to find it</h3><div className="source-links">{links(d).map(x=><a key={x.url} href={x.url} target="_blank" rel="noreferrer"><ExternalLink size={13}/>{x.label}</a>)}</div></section>
 <section className="detail-section"><label>Private notes<textarea value={note} onChange={e=>{setNote(e.target.value);setD({...d,notes:e.target.value})}} placeholder="Your notes…"/></label></section>
 <div className="detail-actions"><button className="primary" onClick={()=>save({...d,notes:note})}><Check size={16}/>Save changes</button><button className="secondary active" onClick={()=>setD({...d,favorite:!d.favorite})}><Heart size={16} fill={d.favorite?'currentColor':'none'}/>{d.favorite?'Favorited':'Favorite'}</button></div></aside></div>;
}
