import { useMemo, useState } from 'react';
import { Bell, BookOpen, CalendarDays, ChevronRight, CirclePlus, Compass, Film, Heart, Home, Library, LogOut, Menu, Search, Settings, Sparkles, Star, Play, Tv, X, BookMarked } from 'lucide-react';
import { signOut, useAuth } from './auth/Auth';
import type { MediaItem, MediaStatus } from './types';

const poster='https://cdn.myanimelist.net/images/anime/10/47347.jpg';
const starter:MediaItem[]=[
{id:'aot',title:'Attack on Titan',subtitle:'Complete main anime',image:poster,backdrop:'https://images.unsplash.com/photo-1519608487953-e999c86e7455?auto=format&fit=crop&w=1800&q=85',status:'completed',current:89,total:89,year:2013,score:9.8,description:'A complete franchise entry with seasons, parts and finale specials organized under one title.',genres:['Action','Dark Fantasy','Mystery'],studio:'WIT Studio / MAPPA',kind:'series',medium:'anime',isFavorite:true},
{id:'sg',title:'Steins;Gate',subtitle:'The original series',image:'https://cdn.myanimelist.net/images/anime/5/43399.jpg',status:'completed',current:24,total:24,year:2011,score:10,description:'A fully watched classic tracked as the parent entry for related releases.',genres:['Sci-Fi','Thriller','Drama'],studio:'White Fox',kind:'series',medium:'anime',isFavorite:true},
{id:'mushoku',title:'Mushoku Tensei',subtitle:'Season tracking',image:'https://cdn.myanimelist.net/images/anime/1015/117695.jpg',status:'watching',current:24,total:24,year:2021,score:8.7,description:'Your current watch list entry.',genres:['Adventure','Fantasy'],studio:'Studio Bind',kind:'series',medium:'anime'},
{id:'rezero',title:'Re:ZERO',subtitle:'Return by Death',image:'https://cdn.myanimelist.net/images/anime/11/79410.jpg',status:'watching',current:66,total:66,year:2016,score:8.8,description:'A long-running fantasy series in your active library.',genres:['Fantasy','Drama','Psychological'],studio:'White Fox',kind:'series',medium:'anime'}
];
const statusLabel:Record<MediaStatus,string>={watching:'Watching',completed:'Completed',plan:'Plan to Watch',paused:'Paused',dropped:'Dropped'};

export default function App(){
 const {user}=useAuth();
 const [items,setItems]=useState<MediaItem[]>(()=>{try{return JSON.parse(localStorage.getItem('frame-library')||'null')||starter}catch{return starter}});
 const [page,setPage]=useState('home'),[query,setQuery]=useState(''),[selected,setSelected]=useState<MediaItem|null>(null),[showAdd,setShowAdd]=useState(false),[mobileMenu,setMobileMenu]=useState(false);
 const save=(next:MediaItem[])=>{setItems(next);localStorage.setItem('frame-library',JSON.stringify(next))};
 const filtered=useMemo(()=>items.filter(x=>x.title.toLowerCase().includes(query.toLowerCase())),[items,query]);
 const watching=items.filter(x=>x.status==='watching'),favorites=items.filter(x=>x.isFavorite);
 const nav=[['home','Home',Home],['library','Library',Library],['discover','Discover',Compass],['calendar','Release Radar',CalendarDays]] as const;
 return <div className="app">
  <header className="topbar"><button className="brand" onClick={()=>setPage('home')}><span>F</span>FRAME</button><nav className="desktop-nav">{nav.map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={17}/>{label}</button>)}</nav><div className="top-actions"><label className="search"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search your library"/></label><button className="icon-btn"><Bell size={18}/></button><button className="avatar" onClick={()=>setPage('settings')}>{(user?.email?.[0]||'F').toUpperCase()}</button><button className="mobile-menu-btn icon-btn" onClick={()=>setMobileMenu(!mobileMenu)}>{mobileMenu?<X/>:<Menu/>}</button></div></header>
  {mobileMenu&&<div className="mobile-nav">{nav.map(([id,label,Icon])=><button key={id} onClick={()=>{setPage(id);setMobileMenu(false)}}><Icon size={18}/>{label}</button>)}</div>}
  <main>{page==='home'&&<HomePage items={items} watching={watching} favorites={favorites} onOpen={setSelected} onAdd={()=>setShowAdd(true)}/>} {page==='library'&&<LibraryPage items={filtered} query={query} onOpen={setSelected} onAdd={()=>setShowAdd(true)}/>} {page==='discover'&&<Discover onAdd={()=>setShowAdd(true)}/>} {page==='calendar'&&<Calendar/>} {page==='settings'&&<SettingsPage email={user?.email||''}/>}</main>
  <div className="mobile-tabs">{nav.slice(0,3).map(([id,label,Icon])=><button key={id} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon size={19}/><span>{label}</span></button>)}<button onClick={()=>setPage('settings')}><Settings size={19}/><span>Settings</span></button></div>
  {selected&&<Detail item={selected} close={()=>setSelected(null)} save={next=>save(items.map(x=>x.id===next.id?next:x))}/>} {showAdd&&<AddModal close={()=>setShowAdd(false)} add={item=>save([item,...items])}/>}
 </div>;
}
function HomePage({items,watching,favorites,onOpen,onAdd}:{items:MediaItem[];watching:MediaItem[];favorites:MediaItem[];onOpen:(x:MediaItem)=>void;onAdd:()=>void}){const hero=items[0];return <div className="page"><section className="hero" style={{backgroundImage:'url('+(hero.backdrop||hero.image)+')'}}><div className="hero-shade"/><div className="hero-content"><div className="eyebrow"><Sparkles size={14}/> YOUR MEDIA UNIVERSE</div><h1>{hero.title}</h1><p>{hero.description}</p><div className="hero-meta"><span><Star size={14} fill="currentColor"/> {hero.score}</span><span>{hero.year}</span><span>{hero.genres?.slice(0,3).join(' · ')}</span></div><div className="hero-actions"><button className="primary" onClick={()=>onOpen(hero)}><Play size={17} fill="currentColor"/> Open title</button><button className="secondary" onClick={onAdd}><CirclePlus size={17}/> Add media</button></div></div></section><section className="section stats-row"><Stat label="In library" value={items.length}/><Stat label="Watching" value={watching.length}/><Stat label="Completed" value={items.filter(x=>x.status==='completed').length}/><Stat label="Favorites" value={favorites.length}/></section><Shelf title="Continue watching" items={watching} onOpen={onOpen}/><Shelf title="Your favorites" items={favorites} onOpen={onOpen}/></div>}
function Stat({label,value}:{label:string;value:number}){return <div className="stat"><b>{value}</b><span>{label}</span></div>}
function Shelf({title,items,onOpen}:{title:string;items:MediaItem[];onOpen:(x:MediaItem)=>void}){return <section className="section"><div className="section-head"><div><small>LIBRARY</small><h2>{title}</h2></div><button>View all <ChevronRight size={15}/></button></div><div className="cards">{items.length?items.map(x=><MediaCard key={x.id} item={x} onOpen={onOpen}/>):<div className="empty">Nothing here yet.</div>}</div></section>}
function MediaCard({item,onOpen}:{item:MediaItem;onOpen:(x:MediaItem)=>void}){const progress=item.total?Math.min(100,item.current/item.total*100):0;return <button className="media-card" onClick={()=>onOpen(item)}><div className="poster"><img src={item.image} alt=""/><span className="status">{statusLabel[item.status]}</span><span className="score"><Star size={11} fill="currentColor"/> {item.score??'—'}</span></div><div className="card-copy"><b>{item.title}</b><span>{item.subtitle||item.medium}</span><div className="progress"><i style={{width:progress+'%'}}/></div><small>{item.current}{item.total?' / '+item.total:''} progress</small></div></button>}
function LibraryPage({items,query,onOpen,onAdd}:{items:MediaItem[];query:string;onOpen:(x:MediaItem)=>void;onAdd:()=>void}){return <div className="page padded"><div className="page-title"><div><small>YOUR COLLECTION</small><h1>Library</h1><p>{query?'Results for “'+query+'”':'Everything you follow, organized.'}</p></div><button className="primary" onClick={onAdd}><CirclePlus size={17}/> Add media</button></div><div className="filter-row">{['All','Watching','Completed','Plan to Watch','Paused','Dropped'].map(x=><button key={x}>{x}</button>)}</div><div className="grid">{items.map(x=><MediaCard key={x.id} item={x} onOpen={onOpen}/>)}</div></div>}
function Discover({onAdd}:{onAdd:()=>void}){return <div className="page padded"><div className="page-title"><div><small>EXPLORE</small><h1>Discover</h1><p>Find something worth adding to your universe.</p></div><button className="primary" onClick={onAdd}><Sparkles size={17}/> Add from search</button></div><div className="discover-grid"><div><Tv/><h3>Anime</h3><p>Series, seasons, parts and specials.</p></div><div><BookOpen/><h3>Manga & Manhwa</h3><p>Track chapters, volumes and progress.</p></div><div><Film/><h3>Movies & Series</h3><p>Keep every kind of story together.</p></div><div><BookMarked/><h3>Light & Visual Novels</h3><p>Your complete fiction library.</p></div></div></div>}
function Calendar(){return <div className="page padded"><div className="page-title"><div><small>COMING UP</small><h1>Release Radar</h1><p>Upcoming episodes and chapters will appear here automatically.</p></div></div><div className="radar"><CalendarDays size={28}/><h2>Release tracking is next</h2><p>Once connected, FRAME will watch your tracked titles for you.</p></div></div>}
function SettingsPage({email}:{email:string}){return <div className="page padded"><div className="page-title"><div><small>ACCOUNT</small><h1>Settings</h1><p>Manage your FRAME account and preferences.</p></div></div><div className="settings-card"><div className="profile"><div className="large-avatar">{(email[0]||'F').toUpperCase()}</div><div><b>{email||'FRAME user'}</b><span>Private account</span></div></div><button className="danger" onClick={()=>signOut()}><LogOut size={17}/> Sign out</button></div></div>}
function Detail({item,close,save}:{item:MediaItem;close:()=>void;save:(x:MediaItem)=>void}){const [draft,setDraft]=useState(item);return <div className="overlay"><aside className="drawer"><button className="close" onClick={close}><X/></button><img className="detail-backdrop" src={draft.backdrop||draft.image} alt=""/><div className="detail"><div className="detail-poster"><img src={draft.image} alt=""/></div><div className="detail-main"><small>{draft.medium?.toUpperCase()} · {statusLabel[draft.status]}</small><h2>{draft.title}</h2><p>{draft.description}</p><div className="chips">{draft.genres?.map(g=><span key={g}>{g}</span>)}</div><div className="detail-progress"><div><b>Progress</b><span>{draft.current}{draft.total?' / '+draft.total:''}</span></div><input type="range" min="0" max={draft.total||2000} value={draft.current} onChange={e=>setDraft({...draft,current:Number(e.target.value)})}/></div><div className="detail-actions"><button className="primary" onClick={()=>save(draft)}><Play size={16}/> Save progress</button><button className="secondary" onClick={()=>setDraft({...draft,isFavorite:!draft.isFavorite})}><Heart size={16} fill={draft.isFavorite?'currentColor':'none'}/></button></div></div></div></aside></div>}
function AddModal({close,add}:{close:()=>void;add:(x:MediaItem)=>void}){const [title,setTitle]=useState('');const [type,setType]=useState<MediaItem['medium']>('anime');const submit=(e:React.FormEvent)=>{e.preventDefault();if(!title.trim())return;add({id:crypto.randomUUID(),title:title.trim(),image:poster,status:'plan',current:0,kind:'series',medium:type,genres:[]});close()};return <div className="modal-wrap"><div className="modal"><button className="close" onClick={close}><X/></button><small>ADD TO FRAME</small><h2>Start a new title</h2><p>Add the basics now. Metadata search will make this automatic in the next phase.</p><form onSubmit={submit}><label>Title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} placeholder="e.g. Frieren: Beyond Journey’s End"/></label><label>Media type<select value={type} onChange={e=>setType(e.target.value as MediaItem['medium'])}><option value="anime">Anime</option><option value="manga">Manga</option><option value="manhwa">Manhwa</option><option value="light-novel">Light Novel</option><option value="visual-novel">Visual Novel</option><option value="movie">Movie</option><option value="series">Series</option></select></label><button className="primary full">Add to library</button></form></div></div>}
